name: FastCopy Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    strategy:
      matrix:
        configuration: [Debug, Release]
        os: [windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore FastCopy.sln

    # Build the solution
    - name: Build
      run: dotnet build FastCopy.sln --configuration ${{ matrix.configuration }} --no-restore

    # Publish the application
    - name: Publish
      run: dotnet publish FastCopy.sln --configuration ${{ matrix.configuration }} --no-build --output ./publish

    # Upload the published files as artifacts
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: FastCopy-${{ matrix.configuration }}
        path: ./publish

